fix: Simulation files for each imputation methods
Some imputation methods fail to run on every node of the argument grid.

* Amelia shows with `p=0.35`
```r
error: chol(): decomposition failed
terminate called after throwing an instance of 'std::runtime_error'
  what():  chol(): decomposition failed
```

* Imputeknn displays
```r
 *** caught segfault ***
address (nil), cause 'unknown'
```
For now, I suppose this comes from the fortran code.